# build worker image (VM template)
image: Visual Studio 2017

# default appveyour version
version: 0.0.0.{build}

# install cement and patch appveyour version
install:
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/DmitryZyr/appveyor/master/patch-appveyour-build-version.ps1" -Out "patch-appveyour-build-version.ps1"
  - ps: ./patch-appveyour-build-version.ps1
  - ps: Invoke-WebRequest "https://raw.githubusercontent.com/DmitryZyr/appveyor/master/cement-install.ps1" -Out "cement-install.ps1"
  - ps: ./cement-install.ps1

# version patching
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
   
build_script:
  - cmd: cd .. & call %cm% init & cd %appveyor_build_folder%
  - cmd: call %cm% update-deps -v
  - cmd: call %cm% build-deps -v
  - cmd: call %cm% build

after_test:
  - ps: Get-ChildItem -Recurse -Filter "*.nuspec" | ForEach-Object {nuget pack $_.FullName -Version "$env:APPVEYOR_BUILD_VERSION"}

artifacts:
  - path: '**\*.nupkg'

deploy:
  # Deploying to NuGet feed
  - provider: Environment
    name: FullNuget
    artifact: /.*\.nupkg/
    on:
      branch: master

  # Deploy to GitHub Releases
  - provider: GitHub
    artifact: /.*\.nupkg/
    on:
      branch: master
      appveyor_repo_tag: true